apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ftuv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0037-tenant/tkrw-pr712-0075-0037-app/devfile-sample-ftuv@sha256:4b7e2e0ad389666bbf4a168e4d75f016f9381c6dbc8ec1f04a6c7b849815cac1
        name: my-nodejs
        resources: {}
status: {}
